export const anemiaRules = [
  {
    id: 'anemia_leve_pediatrica',
    pathology: 'anemia',
    levelRequired: ['I-1', 'I-2', 'I-3', 'I-4'],
    conditions: [
      { field: 'edad', operator: 'lessThan', value: 12 },
      { field: 'laboratorio.hemoglobina', operator: 'greaterThan', value: 9.9 },
      { field: 'laboratorio.hemoglobina', operator: 'lessThan', value: 11 },
    ],
    diagnosis: 'Anemia leve pediátrica',
    severity: 'Leve',
    treatment: {
      firstLine: 'Sulfato ferroso',
      alternative: 'Hierro polimaltosado',
      doseFormula: { mgPorKg: 3, frecuencia: '1 vez al día', dosisMaxima: 60, unit: 'mg' },
    },
    requiredMedications: ['Sulfato ferroso'],
    referralCriteria: 'Control en atención primaria y reevaluación de hemoglobina en 4 semanas.',
    requiresHospitalization: false,
  },
  {
    id: 'anemia_moderada_pediatrica',
    pathology: 'anemia',
    levelRequired: ['I-1', 'I-2', 'I-3', 'I-4'],
    conditions: [
      { field: 'edad', operator: 'lessThan', value: 12 },
      { field: 'laboratorio.hemoglobina', operator: 'greaterThan', value: 6.9 },
      { field: 'laboratorio.hemoglobina', operator: 'lessThan', value: 10 },
    ],
    diagnosis: 'Anemia moderada pediátrica',
    severity: 'Moderada',
    treatment: {
      firstLine: 'Sulfato ferroso',
      alternative: 'Hierro polimaltosado',
      doseFormula: { mgPorKg: 4, frecuencia: '2 veces al día', dosisMaxima: 120, unit: 'mg' },
    },
    requiredMedications: ['Sulfato ferroso'],
    referralCriteria: 'Referir si no responde en 4 semanas',
    requiresHospitalization: false,
  },
  {
    id: 'anemia_severa_pediatrica',
    pathology: 'anemia',
    levelRequired: ['I-1', 'I-2', 'I-3', 'I-4'],
    conditions: [
      { field: 'edad', operator: 'lessThan', value: 12 },
      { field: 'laboratorio.hemoglobina', operator: 'lessThan', value: 7 },
    ],
    diagnosis: 'Anemia severa pediátrica',
    severity: 'Severa',
    treatment: {
      firstLine: 'Estabilización y referencia hospitalaria',
      alternative: 'Sulfato ferroso',
      doseFormula: '0 mg',
    },
    requiredMedications: [],
    referralCriteria: 'Referir de inmediato para transfusión si Hb < 5',
    requiresHospitalization: true,
  },
  {
    id: 'anemia_gestante_leve',
    pathology: 'anemia',
    levelRequired: ['I-1', 'I-2', 'I-3', 'I-4'],
    conditions: [
      { field: 'sexo', operator: 'equals', value: 'F' },
      { field: 'edad', operator: 'greaterThan', value: 12 },
      { field: 'laboratorio.hemoglobina', operator: 'greaterThan', value: 9.9 },
      { field: 'laboratorio.hemoglobina', operator: 'lessThan', value: 11 },
    ],
    diagnosis: 'Anemia leve en gestante',
    severity: 'Leve',
    treatment: {
      firstLine: 'Sulfato ferroso 300mg',
      alternative: 'Sulfato ferroso',
      doseFormula: '300 mg',
    },
    requiredMedications: ['Sulfato ferroso 300mg'],
    referralCriteria: 'Control prenatal con reevaluación de hemoglobina según NTS vigente.',
    requiresHospitalization: false,
  },
  {
    id: 'anemia_gestante_moderada',
    pathology: 'anemia',
    levelRequired: ['I-3', 'I-4'],
    conditions: [
      { field: 'sexo', operator: 'equals', value: 'F' },
      { field: 'edad', operator: 'greaterThan', value: 12 },
      { field: 'laboratorio.hemoglobina', operator: 'lessThan', value: 10 },
    ],
    diagnosis: 'Anemia moderada en gestante',
    severity: 'Moderada',
    treatment: {
      firstLine: 'Hierro sacarosa IV',
      alternative: 'Sulfato ferroso 300mg',
      doseFormula: '200 mg',
    },
    requiredMedications: ['Hierro sacarosa IV'],
    referralCriteria: 'Referir si no mejora con terapia parenteral o presenta signos de inestabilidad materna.',
    requiresHospitalization: false,
  },
];
